### ISSUE TITLE
Error handling large-scale data in crop or mask functions

### ISSUE THREAD

**Issue by Breeze-Hu** [rspatial/terra#1692]
Happy New Year!

Recently, when dealing with a large-scale data crop, I got an error when using terra `crop` or `mask`.
Although I tried the following:  `terraOptions(memfrac = 0.9, progress = 6)`
```
Error: [mask] too many values for writing: 146475876 > 135216727
```
Finally use `terraOptions(memfrac = 0.98, progress = 6)` before crop gets run. 

Even though my Mac is only 18G, I think the size of the data (Approximately 350MB) is far from filling up the memory.
Is this a mechanism to avoid bursting memory?

**Comment by rhijmans** [comment]
Thank you for reporting this. This message should never be given. Unfortunately, as you are not following the instructions for submitting issues, there is nothing I can do with your report.

**Comment by Breeze-Hu** [comment]
Dear Robert Hijmans,

I apologize for misjudging the complexity of this issue.
I uploaded the raw data used: [example data](https://drive.google.com/drive/folders/1PhHgjuEe7DKeabKG_wZWL63Q3b8f0f0d?usp=share_link)
The code to reproduce the problem is below:
```
library(terra)
library(sf)

area <- st_read('./example data/china.geojson') |> 
  st_transform(crs = 'epsg:4326')

dem <- rast('./example data/dem500.tif') |> 
  project(y = crs(area))

dem_crop <- crop(dem, ext(area))

#dem <- mask(dem_crop, mask = area)
#Error: [mask] too many values for writing: 146475876 > 51712645
#In addition: Warning message:
#[SpatVector from sf] not all geometries were transferred, use svc for a geometry collection

dem <- mask(dem_crop, mask = area[2,])
#Error: [mask] too many values for writing: 146475876 > 57808168
```


It would be convenient if this warning issue: `[SpatVector from sf] not all geometries were transferred, use svc for a geometry collection` could be dealt with.

**Comment by francisvolh** [comment]
Just to reinforce this issue, I have just bumped into the exact same error just now, after re-running some code that worked about 7 month ago
. 
```
>   maskedTest <- terra::mask(  elevationCrop2 , NA_CEC_Eco_Level2crop  )
Error: [mask] too many values for writing: 79910080 > 77894000
```
I am using terra version ‘1.8.5’, but this worked with an earlier version of terra. 


I basically produced an NA mask of ocean values using an elevation raster and a polygon outline. 
![image](https://github.com/user-attachments/assets/7d5c2e1f-eb2a-422f-a158-96d32f25fb3e)

Regretfully the raster files is fairly large and the polygon compiles multiple others for North America, but I could upload them if needed, but I think they will just make the same point of the above China example. 

The raster has this features:
```
> elevationCrop2
class       : SpatRaster 
dimensions  : 8720, 9164, 1  (nrow, ncol, nlyr)
resolution  : 530.5138, 530.5138  (x, y)
extent      : -4904478, -42849.44, -352547.7, 4273533  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
source      : spat_33b876562dab_13240_o8up7yuDdJ6XHBX.tif 
name        : elevation_1KMmd_GMTEDmd 
min value   :                  -1.000 
max value   :                5898.243
```
And the polygons as follows:
```
> NA_CEC_Eco_Level2crop
 class       : SpatVector 
 geometry    : polygons 
 dimensions  : 617, 12  (geometries, attributes)
 extent      : -4376231, -42849.44, -352547.7, 3912439  (xmin, xmax, ymin, ymax)
 coord. ref. : +proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
 names       : LEVEL1       NameL1_En       NameL1_Es       NameL1_Fr LEVEL2    NameL2_En       NameL2_Es      NameL2_Fr
 type        :  <chr>           <chr>           <chr>           <chr>  <chr>        <chr>           <chr>          <chr>
 values      :     10 North American~ Desiertos de A~ Déserts de l'A~   10.1 Cold Deserts Desiertos fríos Déserts froids
                   10 North American~ Desiertos de A~ Déserts de l'A~   10.1 Cold Deserts Desiertos fríos Déserts froids
                   10 North American~ Desiertos de A~ Déserts de l'A~   10.1 Cold Deserts Desiertos fríos Déserts froids
          L2Key_En        L2Key_Es        L2Key_Fr Area_SqKm
             <chr>           <chr>           <chr>     <num>
 10.1 Cold Deserts 10.1 Desiertos~ 10.1 Déserts f~ 9.178e+05
 10.1 Cold Deserts 10.1 Desiertos~ 10.1 Déserts f~       109
 10.1 Cold Deserts 10.1 Desiertos~ 10.1 Déserts f~      1765 
```

The error message says the dimensions of the raster 8720 x 9164 (total 79910080 ) are way too may for whatever other size I can pick where its coming from. But this worked fine 7 months ago. 

Thanks for any input!

**Comment by Breeze-Hu** [comment]
> It would be convenient if this warning issue: `[SpatVector from sf] not all geometries were transferred, use svc for a geometry collection` could be dealt with.

Would it be possible to set this section to automatically filter out polygons (or other vectors that can be cropped) when a `crop` or `mask` is made instead of straight warning and failing? Wouldn't that be a more logical way of thinking about the operation?

**Comment by rhijmans** [comment]
@Breeze-Hu's example works for me with the development version. So I think this has been fixed. Please see for yourself with the development version and report back if it still breaks for you. 

 I used this streamlined example (no need for projection as both datasets have the same desired CRS)

```
library(terra)
d <- rast('dem500.tif')
v <- svc('china.geojson')
area <- v[1]
dash <- v[2]
dem_crop <- crop(dem, area, mask=TRUE)
dem <- mask(dem_crop, area)
```

And the last two steps can be combined into

```
dem <- crop(d, area, mask=TRUE)
```

I can get the error in the current CRAN version (1.8-5), although I need to force processing in chunks by adding the chunks argument (suggesting that my computer has more free RAM).

```
dem <- mask(dem_crop, area, steps=4)
#Error: [mask] too many values for writing: 146475876 > 36618969
```


> Would it be possible to set this section to automatically filter out polygons (or other vectors that can be cropped) when a > crop or mask is made instead of straight warning and failing? 

It actually works as intended in this case because the first element of the collection is the polygons (the second element is the dash line). I cannot really guess what a user would want in situations like this.

**Comment by Breeze-Hu** [comment]
Thanks for your advice! @rhijmans 
Currently Mac os can only install up to version 1.8.7 of terra (install.packages('terra', repos='https://rspatial.r-universe.dev')) via R-universe. My test results based on this version are as follows:

You can see that both vector and raster data are readable, but there is still an error in the final `crop`. I will test again in a subsequent update.
```
library(terra)
terra 1.8.7
> v <- svc('/Users/sy/Documents/liuyu/中国_边境线.geojson')
> area <- v[1]
> area
 class       : SpatVector 
 geometry    : polygons 
 dimensions  : 1, 0  (geometries, attributes)
 extent      : 73.49896, 135.0874, 3.832541, 53.5585  (xmin, xmax, ymin, ymax)
 coord. ref. : lon/lat WGS 84 (EPSG:4326) 
> dem <- rast('/Users/sy/Documents/liuyu/code/dem500.tif')
> dem
class       : SpatRaster 
dimensions  : 10085, 17763, 1  (nrow, ncol, nlyr)
resolution  : 0.004031287, 0.004031287  (x, y)
extent      : 66.39632, 138.0041, 14.90839, 55.56392  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : dem500.tif 
name        : dem500 
> crop(dem, area, mask=TRUE)
Error: [crop] mask raster has no values-| 
```

**Comment by kadyb** [comment]
@Breeze-Hu, version 1.8.9 (current dev) is now available on [R-Universe](https://rspatial.r-universe.dev/terra).

**Comment by Breeze-Hu** [comment]
Great! After updating to version 1.8.9, everything works as expected.
Thank you for your contributions！
